// src/lib/zh/AboutMe.svelte
<main>
    <div>
        <p style="color: darkgrey;">
            he/him
        </p>
        <p>
            本预润英小留 目前就读于曼大计算机专业
        </p>
        <p>
            编程苦手，技术栈：
        </p>
        <p style="display:inline;margin-left: min(4vw, 1em);">
            后端Golang C# Python
        </p><br>
        <p style="display:inline;margin-left: min(4vw, 1em);">
            前端Vue Svelte
        </p><br>
        <p>
            爱好折腾，日用<s>NixOS</s> Arch Linux + Win11
        </p>
        <p>
            喜欢的颜色：<span style="color: #00B294;">#00B294</span>（非常喜欢
        </p>
    </div>
</main>

<style>
    @import '../style/AboutMe.css';
</style>

// src/components/AboutMe.vue
<template>
  <div>
    <p style="color: darkgrey;">he/him</p>
    <p>本预润英小留</p>
    <p>编程苦手，技术栈：<br>
      <p style="display:inline;margin-left: min(4vw, 1em);">后端Golang C# Python</p><br>
      <p style="display:inline;margin-left: min(4vw, 1em);">前端Vue，但是不会TS</p><br>
    </p>
    <p style="color: darkgray;">从这个主页你应该看得出我的代码水平有多烂</p>
    <p>爱好折腾，日用Win11 + <s>NixOS</s> Arch Linux</p>
    <p>喜欢的颜色：<span style="color: #00B294;">#00B294</span>（非常喜欢</p>
  </div>
</template>

<style scoped>
p {
  color: #f2f2f7;
  font-size: min(4vw, 1em);
  margin-top: 1vh;
  margin-bottom: 1vh;
}
</style>
