// src/components/AboutMe.vue
<template>
  <div>
    <p style="color: darkgrey;">he/him</p>
    <p>本预润英小留</p>
    <p>编程苦手，技术栈：<br>
      <p style="display:inline;margin-left: min(4vw, 1em);">后端Golang C# Python</p><br>
      <p style="display:inline;margin-left: min(4vw, 1em);">前端Vue，但是不会TS</p><br>
    </p>
    <p style="color: darkgray;">从这个主页你应该看得出我的代码水平有多烂</p>
    <p>爱好折腾，日用Win11 + <s>NixOS</s> Arch Linux</p>
    <p>喜欢的颜色：<span style="color: #00B294;">#00B294</span>（非常喜欢</p>
  </div>
</template>

<style scoped>
p {
  color: #f2f2f7;
  font-size: min(4vw, 1em);
  margin-top: 1vh;
  margin-bottom: 1vh;
}
</style>

// src/lib/en/AboutMe.svelte
<main>
    <p style="color: darkgrey;">
        he/him
    </p>
    <p>
        First year student at the University of Manchester, studying Computer Science
    </p>
    <p>
        Tech Stack:
    </p>
    <p style="display:inline;margin-left: min(4vw, 1em);">
        Backend: Golang C# Python
    </p><br>
    <p style="display:inline;margin-left: min(4vw, 1em);">
        Frontend: Vue Svelte
    </p><br>
    <p>
        Tech nerd, daily using <s>NixOS</s> Arch Linux + Win11
    </p>
    <p>
        My favorite color: <span style="color: #00B294;">#00B294</span>
    </p>
</main>

<style>
    @import '../style/AboutMe.css';
</style>
